[package]
name = "render-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "librender"
path = "src/lib.rs"

[[bin]]
name = "render-bin"
path = "src/main.rs"

[profile.release]
lto = true
